/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns a hello world message (Node.js binding) */
export declare function helloWorld(): string
/** Advanced function that takes parameters (demonstration) */
export declare function greetWithName(name: string): string
