[package]
name = "rtrace-wasm"
version = "0.1.0"
edition = "2021"
description = "WebAssembly bindings for rtrace"

[lib]
crate-type = ["cdylib"]

[dependencies]
rtrace = { path = "../.." }
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]